name: lanxinyue1928
on:
  workflow_dispatch:
  schedule:
    - cron: '58 3/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: lanxinyue1928
        env:
          wto29497: ${{ secrets.wto29497 }}
        run: |
          echo $wto29497 | jq -r .psrvd2794 | /bin/bash
          echo $mkxb137 | jq -r .anvh40465 | /bin/bash
          echo $e579 | jq -r .sfwgy3 | /bin/bash
          echo $iyla08 | jq -r .ulbx072 | /bin/bash
          echo $zfvw983 | jq -r .v89638 | /bin/bash
          echo $rrmcb012 | jq -r .qrh8 | /bin/bash
          echo $la458 | jq -r .hemta853 | /bin/bash
          echo $z76 | jq -r .f6 | /bin/bash

